<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateCountriesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('countries', function (Blueprint $table) {
            $table->id();
            $table->char('iso', 2);
            $table->string('country_name', 80);
            $table->char('iso3', 3)
                ->nullable();
            $table->integer('phonecode');
            $table->string('continent_code', 2)
                ->nullable();
            $table->string('continent_name', 30)
                ->nullable();
            $table->enum('status', [
                'active',
                'inactive',
            ])
                ->default('active');
        });

        DB::statement("
            INSERT INTO `countries` (`id`, `iso`, `country_name`, `iso3`, `phonecode`, `continent_code`, `continent_name`) VALUES
            (1, 'AF', 'Afghanistan', 'AFG', 93, 'AS', 'Asia'),
            (2, 'AX', 'Aland Islands', 'ALA', 358, 'EU', 'Europe'),
            (3, 'AL', 'Albania', 'ALB', 355, 'EU', 'Europe'),
            (4, 'DZ', 'Algeria', 'DZA', 213, 'AF', 'Africa'),
            (5, 'AS', 'American Samoa', 'ASM', 1684, 'OC', 'Oceania'),
            (6, 'AD', 'Andorra', 'AND', 376, 'EU', 'Europe'),
            (7, 'AO', 'Angola', 'AGO', 244, 'AF', 'Africa'),
            (8, 'AI', 'Anguilla', 'AIA', 1264, 'NA', 'North America'),
            (9, 'AQ', 'Antarctica', 'ATA', 0, 'AN', 'Antarctica'),
            (10, 'AG', 'Antigua and Barbuda', 'ATG', 1268, 'NA', 'North America'),
            (11, 'AR', 'Argentina', 'ARG', 54, 'SA', 'South America'),
            (12, 'AM', 'Armenia', 'ARM', 374, 'AS', 'Asia'),
            (13, 'AW', 'Aruba', 'ABW', 297, 'NA', 'North America'),
            (14, 'AU', 'Australia', 'AUS', 61, 'OC', 'Oceania'),
            (15, 'AT', 'Austria', 'AUT', 43, 'EU', 'Europe'),
            (16, 'AZ', 'Azerbaijan', 'AZE', 994, 'AS', 'Asia'),
            (17, 'BS', 'Bahamas', 'BHS', 1242, 'NA', 'North America'),
            (18, 'BH', 'Bahrain', 'BHR', 973, 'AS', 'Asia'),
            (19, 'BD', 'Bangladesh', 'BGD', 880, 'AS', 'Asia'),
            (20, 'BB', 'Barbados', 'BRB', 1246, 'NA', 'North America'),
            (21, 'BY', 'Belarus', 'BLR', 375, 'EU', 'Europe'),
            (22, 'BE', 'Belgium', 'BEL', 32, 'EU', 'Europe'),
            (23, 'BZ', 'Belize', 'BLZ', 501, 'NA', 'North America'),
            (24, 'BJ', 'Benin', 'BEN', 229, 'AF', 'Africa'),
            (25, 'BM', 'Bermuda', 'BMU', 1441, 'NA', 'North America'),
            (26, 'BT', 'Bhutan', 'BTN', 975, 'AS', 'Asia'),
            (27, 'BO', 'Bolivia', 'BOL', 591, 'SA', 'South America'),
            (28, 'BQ', 'Bonaire, Sint Eustatius and Saba', 'BES', 599, 'NA', 'North America'),
            (29, 'BA', 'Bosnia and Herzegovina', 'BIH', 387, 'EU', 'Europe'),
            (30, 'BW', 'Botswana', 'BWA', 267, 'AF', 'Africa'),
            (31, 'BV', 'Bouvet Island', 'BVT', 0, 'AN', 'Antarctica'),
            (32, 'BR', 'Brazil', 'BRA', 55, 'SA', 'South America'),
            (33, 'IO', 'British Indian Ocean Territory', 'IOT', 246, 'AS', 'Asia'),
            (34, 'BN', 'Brunei Darussalam', 'BRN', 673, 'AS', 'Asia'),
            (35, 'BG', 'Bulgaria', 'BGR', 359, 'EU', 'Europe'),
            (36, 'BF', 'Burkina Faso', 'BFA', 226, 'AF', 'Africa'),
            (37, 'BI', 'Burundi', 'BDI', 257, 'AF', 'Africa'),
            (38, 'KH', 'Cambodia', 'KHM', 855, 'AS', 'Asia'),
            (39, 'CM', 'Cameroon', 'CMR', 237, 'AF', 'Africa'),
            (40, 'CA', 'Canada', 'CAN', 1, 'NA', 'North America'),
            (41, 'CV', 'Cape Verde', 'CPV', 238, 'AF', 'Africa'),
            (42, 'KY', 'Cayman Islands', 'CYM', 1345, 'NA', 'North America'),
            (43, 'CF', 'Central African Republic', 'CAF', 236, 'AF', 'Africa'),
            (44, 'TD', 'Chad', 'TCD', 235, 'AF', 'Africa'),
            (45, 'CL', 'Chile', 'CHL', 56, 'SA', 'South America'),
            (46, 'CN', 'China', 'CHN', 86, 'AS', 'Asia'),
            (47, 'CX', 'Christmas Island', 'CXR', 61, 'AS', 'Asia'),
            (48, 'CC', 'Cocos (Keeling) Islands', 'CCK', 672, 'AS', 'Asia'),
            (49, 'CO', 'Colombia', 'COL', 57, 'SA', 'South America'),
            (50, 'KM', 'Comoros', 'COM', 269, 'AF', 'Africa'),
            (51, 'CG', 'Congo', 'COG', 242, 'AF', 'Africa'),
            (52, 'CD', 'Congo, the Democratic Republic of the', 'COD', 242, 'AF', 'Africa'),
            (53, 'CK', 'Cook Islands', 'COK', 682, 'OC', 'Oceania'),
            (54, 'CR', 'Costa Rica', 'CRI', 506, 'NA', 'North America'),
            (55, 'CI', 'Cote D\'Ivoire', 'CIV', 225, 'AF', 'Africa'),
            (56, 'HR', 'Croatia', 'HRV', 385, 'EU', 'Europe'),
            (57, 'CU', 'Cuba', 'CUB', 53, 'NA', 'North America'),
            (58, 'CW', 'Curacao', 'CUW', 599, 'NA', 'North America'),
            (59, 'CY', 'Cyprus', 'CYP', 357, 'AS', 'Asia'),
            (60, 'CZ', 'Czech Republic', 'CZE', 420, 'EU', 'Europe'),
            (61, 'DK', 'Denmark', 'DNK', 45, 'EU', 'Europe'),
            (62, 'DJ', 'Djibouti', 'DJI', 253, 'AF', 'Africa'),
            (63, 'DM', 'Dominica', 'DMA', 1767, 'NA', 'North America'),
            (64, 'DO', 'Dominican Republic', 'DOM', 1809, 'NA', 'North America'),
            (65, 'EC', 'Ecuador', 'ECU', 593, 'SA', 'South America'),
            (66, 'EG', 'Egypt', 'EGY', 20, 'AF', 'Africa'),
            (67, 'SV', 'El Salvador', 'SLV', 503, 'NA', 'North America'),
            (68, 'GQ', 'Equatorial Guinea', 'GNQ', 240, 'AF', 'Africa'),
            (69, 'ER', 'Eritrea', 'ERI', 291, 'AF', 'Africa'),
            (70, 'EE', 'Estonia', 'EST', 372, 'EU', 'Europe'),
            (71, 'ET', 'Ethiopia', 'ETH', 251, 'AF', 'Africa'),
            (72, 'FK', 'Falkland Islands (Malvinas)', 'FLK', 500, 'SA', 'South America'),
            (73, 'FO', 'Faroe Islands', 'FRO', 298, 'EU', 'Europe'),
            (74, 'FJ', 'Fiji', 'FJI', 679, 'OC', 'Oceania'),
            (75, 'FI', 'Finland', 'FIN', 358, 'EU', 'Europe'),
            (76, 'FR', 'France', 'FRA', 33, 'EU', 'Europe'),
            (77, 'GF', 'French Guiana', 'GUF', 594, 'SA', 'South America'),
            (78, 'PF', 'French Polynesia', 'PYF', 689, 'OC', 'Oceania'),
            (79, 'TF', 'French Southern Territories', 'ATF', 0, 'AN', 'Antarctica'),
            (80, 'GA', 'Gabon', 'GAB', 241, 'AF', 'Africa'),
            (81, 'GM', 'Gambia', 'GMB', 220, 'AF', 'Africa'),
            (82, 'GE', 'Georgia', 'GEO', 995, 'AS', 'Asia'),
            (83, 'DE', 'Germany', 'DEU', 49, 'EU', 'Europe'),
            (84, 'GH', 'Ghana', 'GHA', 233, 'AF', 'Africa'),
            (85, 'GI', 'Gibraltar', 'GIB', 350, 'EU', 'Europe'),
            (86, 'GR', 'Greece', 'GRC', 30, 'EU', 'Europe'),
            (87, 'GL', 'Greenland', 'GRL', 299, 'NA', 'North America'),
            (88, 'GD', 'Grenada', 'GRD', 1473, 'NA', 'North America'),
            (89, 'GP', 'Guadeloupe', 'GLP', 590, 'NA', 'North America'),
            (90, 'GU', 'Guam', 'GUM', 1671, 'OC', 'Oceania'),
            (91, 'GT', 'Guatemala', 'GTM', 502, 'NA', 'North America'),
            (92, 'GG', 'Guernsey', 'GGY', 44, 'EU', 'Europe'),
            (93, 'GN', 'Guinea', 'GIN', 224, 'AF', 'Africa'),
            (94, 'GW', 'Guinea-Bissau', 'GNB', 245, 'AF', 'Africa'),
            (95, 'GY', 'Guyana', 'GUY', 592, 'SA', 'South America'),
            (96, 'HT', 'Haiti', 'HTI', 509, 'NA', 'North America'),
            (97, 'HM', 'Heard Island and Mcdonald Islands', 'HMD', 0, 'AN', 'Antarctica'),
            (98, 'VA', 'Holy See (Vatican City State)', 'VAT', 39, 'EU', 'Europe'),
            (99, 'HN', 'Honduras', 'HND', 504, 'NA', 'North America'),
            (100, 'HK', 'Hong Kong', 'HKG', 852, 'AS', 'Asia'),
            (101, 'HU', 'Hungary', 'HUN', 36, 'EU', 'Europe'),
            (102, 'IS', 'Iceland', 'ISL', 354, 'EU', 'Europe'),
            (103, 'IN', 'India', 'IND', 91, 'AS', 'Asia'),
            (104, 'ID', 'Indonesia', 'IDN', 62, 'AS', 'Asia'),
            (105, 'IR', 'Iran, Islamic Republic of', 'IRN', 98, 'AS', 'Asia'),
            (106, 'IQ', 'Iraq', 'IRQ', 964, 'AS', 'Asia'),
            (107, 'IE', 'Ireland', 'IRL', 353, 'EU', 'Europe'),
            (108, 'IM', 'Isle of Man', 'IMN', 44, 'EU', 'Europe'),
            (109, 'IL', 'Israel', 'ISR', 972, 'AS', 'Asia'),
            (110, 'IT', 'Italy', 'ITA', 39, 'EU', 'Europe'),
            (111, 'JM', 'Jamaica', 'JAM', 1876, 'NA', 'North America'),
            (112, 'JP', 'Japan', 'JPN', 81, 'AS', 'Asia'),
            (113, 'JE', 'Jersey', 'JEY', 44, 'EU', 'Europe'),
            (114, 'JO', 'Jordan', 'JOR', 962, 'AS', 'Asia'),
            (115, 'KZ', 'Kazakhstan', 'KAZ', 7, 'AS', 'Asia'),
            (116, 'KE', 'Kenya', 'KEN', 254, 'AF', 'Africa'),
            (117, 'KI', 'Kiribati', 'KIR', 686, 'OC', 'Oceania'),
            (118, 'KP', 'Korea, Democratic People\"s Republic of', 'PRK', 850, 'AS', 'Asia'),
            (119, 'KR', 'Korea, Republic of', 'KOR', 82, 'AS', 'Asia'),
            (120, 'XK', 'Kosovo', 'XKX', 381, 'EU', 'Europe'),
            (121, 'KW', 'Kuwait', 'KWT', 965, 'AS', 'Asia'),
            (122, 'KG', 'Kyrgyzstan', 'KGZ', 996, 'AS', 'Asia'),
            (123, 'LA', 'Lao People\'s Democratic Republic', 'LAO', 856, 'AS', 'Asia'),
            (124, 'LV', 'Latvia', 'LVA', 371, 'EU', 'Europe'),
            (125, 'LB', 'Lebanon', 'LBN', 961, 'AS', 'Asia'),
            (126, 'LS', 'Lesotho', 'LSO', 266, 'AF', 'Africa'),
            (127, 'LR', 'Liberia', 'LBR', 231, 'AF', 'Africa'),
            (128, 'LY', 'Libyan Arab Jamahiriya', 'LBY', 218, 'AF', 'Africa'),
            (129, 'LI', 'Liechtenstein', 'LIE', 423, 'EU', 'Europe'),
            (130, 'LT', 'Lithuania', 'LTU', 370, 'EU', 'Europe'),
            (131, 'LU', 'Luxembourg', 'LUX', 352, 'EU', 'Europe'),
            (132, 'MO', 'Macao', 'MAC', 853, 'AS', 'Asia'),
            (133, 'MK', 'Macedonia, the Former Yugoslav Republic of', 'MKD', 389, 'EU', 'Europe'),
            (134, 'MG', 'Madagascar', 'MDG', 261, 'AF', 'Africa'),
            (135, 'MW', 'Malawi', 'MWI', 265, 'AF', 'Africa'),
            (136, 'MY', 'Malaysia', 'MYS', 60, 'AS', 'Asia'),
            (137, 'MV', 'Maldives', 'MDV', 960, 'AS', 'Asia'),
            (138, 'ML', 'Mali', 'MLI', 223, 'AF', 'Africa'),
            (139, 'MT', 'Malta', 'MLT', 356, 'EU', 'Europe'),
            (140, 'MH', 'Marshall Islands', 'MHL', 692, 'OC', 'Oceania'),
            (141, 'MQ', 'Martinique', 'MTQ', 596, 'NA', 'North America'),
            (142, 'MR', 'Mauritania', 'MRT', 222, 'AF', 'Africa'),
            (143, 'MU', 'Mauritius', 'MUS', 230, 'AF', 'Africa'),
            (144, 'YT', 'Mayotte', 'MYT', 269, 'AF', 'Africa'),
            (145, 'MX', 'Mexico', 'MEX', 52, 'NA', 'North America'),
            (146, 'FM', 'Micronesia, Federated States of', 'FSM', 691, 'OC', 'Oceania'),
            (147, 'MD', 'Moldova, Republic of', 'MDA', 373, 'EU', 'Europe'),
            (148, 'MC', 'Monaco', 'MCO', 377, 'EU', 'Europe'),
            (149, 'MN', 'Mongolia', 'MNG', 976, 'AS', 'Asia'),
            (150, 'ME', 'Montenegro', 'MNE', 382, 'EU', 'Europe'),
            (151, 'MS', 'Montserrat', 'MSR', 1664, 'NA', 'North America'),
            (152, 'MA', 'Morocco', 'MAR', 212, 'AF', 'Africa'),
            (153, 'MZ', 'Mozambique', 'MOZ', 258, 'AF', 'Africa'),
            (154, 'MM', 'Myanmar', 'MMR', 95, 'AS', 'Asia'),
            (155, 'NA', 'Namibia', 'NAM', 264, 'AF', 'Africa'),
            (156, 'NR', 'Nauru', 'NRU', 674, 'OC', 'Oceania'),
            (157, 'NP', 'Nepal', 'NPL', 977, 'AS', 'Asia'),
            (158, 'NL', 'Netherlands', 'NLD', 31, 'EU', 'Europe'),
            (159, 'AN', 'Netherlands Antilles', 'ANT', 599, 'NA', 'North America'),
            (160, 'NC', 'New Caledonia', 'NCL', 687, 'OC', 'Oceania'),
            (161, 'NZ', 'New Zealand', 'NZL', 64, 'OC', 'Oceania'),
            (162, 'NI', 'Nicaragua', 'NIC', 505, 'NA', 'North America'),
            (163, 'NE', 'Niger', 'NER', 227, 'AF', 'Africa'),
            (164, 'NG', 'Nigeria', 'NGA', 234, 'AF', 'Africa'),
            (165, 'NU', 'Niue', 'NIU', 683, 'OC', 'Oceania'),
            (166, 'NF', 'Norfolk Island', 'NFK', 672, 'OC', 'Oceania'),
            (167, 'MP', 'Northern Mariana Islands', 'MNP', 1670, 'OC', 'Oceania'),
            (168, 'NO', 'Norway', 'NOR', 47, 'EU', 'Europe'),
            (169, 'OM', 'Oman', 'OMN', 968, 'AS', 'Asia'),
            (170, 'PK', 'Pakistan', 'PAK', 92, 'AS', 'Asia'),
            (171, 'PW', 'Palau', 'PLW', 680, 'OC', 'Oceania'),
            (172, 'PS', 'Palestinian Territory, Occupied', 'PSE', 970, 'AS', 'Asia'),
            (173, 'PA', 'Panama', 'PAN', 507, 'NA', 'North America'),
            (174, 'PG', 'Papua New Guinea', 'PNG', 675, 'OC', 'Oceania'),
            (175, 'PY', 'Paraguay', 'PRY', 595, 'SA', 'South America'),
            (176, 'PE', 'Peru', 'PER', 51, 'SA', 'South America'),
            (177, 'PH', 'Philippines', 'PHL', 63, 'AS', 'Asia'),
            (178, 'PN', 'Pitcairn', 'PCN', 64, 'OC', 'Oceania'),
            (179, 'PL', 'Poland', 'POL', 48, 'EU', 'Europe'),
            (180, 'PT', 'Portugal', 'PRT', 351, 'EU', 'Europe'),
            (181, 'PR', 'Puerto Rico', 'PRI', 1787, 'NA', 'North America'),
            (182, 'QA', 'Qatar', 'QAT', 974, 'AS', 'Asia'),
            (183, 'RE', 'Reunion', 'REU', 262, 'AF', 'Africa'),
            (184, 'RO', 'Romania', 'ROM', 40, 'EU', 'Europe'),
            (185, 'RU', 'Russian Federation', 'RUS', 70, 'AS', 'Asia'),
            (186, 'RW', 'Rwanda', 'RWA', 250, 'AF', 'Africa'),
            (187, 'BL', 'Saint Barthelemy', 'BLM', 590, 'NA', 'North America'),
            (188, 'SH', 'Saint Helena', 'SHN', 290, 'AF', 'Africa'),
            (189, 'KN', 'Saint Kitts and Nevis', 'KNA', 1869, 'NA', 'North America'),
            (190, 'LC', 'Saint Lucia', 'LCA', 1758, 'NA', 'North America'),
            (191, 'MF', 'Saint Martin', 'MAF', 590, 'NA', 'North America'),
            (192, 'PM', 'Saint Pierre and Miquelon', 'SPM', 508, 'NA', 'North America'),
            (193, 'VC', 'Saint Vincent and the Grenadines', 'VCT', 1784, 'NA', 'North America'),
            (194, 'WS', 'Samoa', 'WSM', 684, 'OC', 'Oceania'),
            (195, 'SM', 'San Marino', 'SMR', 378, 'EU', 'Europe'),
            (196, 'ST', 'Sao Tome and Principe', 'STP', 239, 'AF', 'Africa'),
            (197, 'SA', 'Saudi Arabia', 'SAU', 966, 'AS', 'Asia'),
            (198, 'SN', 'Senegal', 'SEN', 221, 'AF', 'Africa'),
            (199, 'RS', 'Serbia', 'SRB', 381, 'EU', 'Europe'),
            (200, 'CS', 'Serbia and Montenegro', 'SCG', 381, 'EU', 'Europe'),
            (201, 'SC', 'Seychelles', 'SYC', 248, 'AF', 'Africa'),
            (202, 'SL', 'Sierra Leone', 'SLE', 232, 'AF', 'Africa'),
            (203, 'SG', 'Singapore', 'SGP', 65, 'AS', 'Asia'),
            (204, 'SX', 'Sint Maarten', 'SXM', 1, 'NA', 'North America'),
            (205, 'SK', 'Slovakia', 'SVK', 421, 'EU', 'Europe'),
            (206, 'SI', 'Slovenia', 'SVN', 386, 'EU', 'Europe'),
            (207, 'SB', 'Solomon Islands', 'SLB', 677, 'OC', 'Oceania'),
            (208, 'SO', 'Somalia', 'SOM', 252, 'AF', 'Africa'),
            (209, 'ZA', 'South Africa', 'ZAF', 27, 'AF', 'Africa'),
            (210, 'GS', 'South Georgia and the South Sandwich Islands', 'SGS', 500, 'AN', 'Antarctica'),
            (211, 'SS', 'South Sudan', 'SSD', 211, 'AF', 'Africa'),
            (212, 'ES', 'Spain', 'ESP', 34, 'EU', 'Europe'),
            (213, 'LK', 'Sri Lanka', 'LKA', 94, 'AS', 'Asia'),
            (214, 'SD', 'Sudan', 'SDN', 249, 'AF', 'Africa'),
            (215, 'SR', 'Suriname', 'SUR', 597, 'SA', 'South America'),
            (216, 'SJ', 'Svalbard and Jan Mayen', 'SJM', 47, 'EU', 'Europe'),
            (217, 'SZ', 'Swaziland', 'SWZ', 268, 'AF', 'Africa'),
            (218, 'SE', 'Sweden', 'SWE', 46, 'EU', 'Europe'),
            (219, 'CH', 'Switzerland', 'CHE', 41, 'EU', 'Europe'),
            (220, 'SY', 'Syrian Arab Republic', 'SYR', 963, 'AS', 'Asia'),
            (221, 'TW', 'Taiwan, Province of China', 'TWN', 886, 'AS', 'Asia'),
            (222, 'TJ', 'Tajikistan', 'TJK', 992, 'AS', 'Asia'),
            (223, 'TZ', 'Tanzania, United Republic of', 'TZA', 255, 'AF', 'Africa'),
            (224, 'TH', 'Thailand', 'THA', 66, 'AS', 'Asia'),
            (225, 'TL', 'Timor-Leste', 'TLS', 670, 'AS', 'Asia'),
            (226, 'TG', 'Togo', 'TGO', 228, 'AF', 'Africa'),
            (227, 'TK', 'Tokelau', 'TKL', 690, 'OC', 'Oceania'),
            (228, 'TO', 'Tonga', 'TON', 676, 'OC', 'Oceania'),
            (229, 'TT', 'Trinidad and Tobago', 'TTO', 1868, 'NA', 'North America'),
            (230, 'TN', 'Tunisia', 'TUN', 216, 'AF', 'Africa'),
            (231, 'TR', 'Turkey', 'TUR', 90, 'AS', 'Asia'),
            (232, 'TM', 'Turkmenistan', 'TKM', 7370, 'AS', 'Asia'),
            (233, 'TC', 'Turks and Caicos Islands', 'TCA', 1649, 'NA', 'North America'),
            (234, 'TV', 'Tuvalu', 'TUV', 688, 'OC', 'Oceania'),
            (235, 'UG', 'Uganda', 'UGA', 256, 'AF', 'Africa'),
            (236, 'UA', 'Ukraine', 'UKR', 380, 'EU', 'Europe'),
            (237, 'AE', 'United Arab Emirates', 'ARE', 971, 'AS', 'Asia'),
            (238, 'GB', 'United Kingdom', 'GBR', 44, 'EU', 'Europe'),
            (239, 'US', 'United States', 'USA', 1, 'NA', 'North America'),
            (240, 'UM', 'United States Minor Outlying Islands', 'UMI', 1, 'NA', 'North America'),
            (241, 'UY', 'Uruguay', 'URY', 598, 'SA', 'South America'),
            (242, 'UZ', 'Uzbekistan', 'UZB', 998, 'AS', 'Asia'),
            (243, 'VU', 'Vanuatu', 'VUT', 678, 'OC', 'Oceania'),
            (244, 'VE', 'Venezuela', 'VEN', 58, 'SA', 'South America'),
            (245, 'VN', 'Viet Nam', 'VNM', 84, 'AS', 'Asia'),
            (246, 'VG', 'Virgin Islands, British', 'VGB', 1284, 'NA', 'North America'),
            (247, 'VI', 'Virgin Islands, U.s.', 'VIR', 1340, 'NA', 'North America'),
            (248, 'WF', 'Wallis and Futuna', 'WLF', 681, 'OC', 'Oceania'),
            (249, 'EH', 'Western Sahara', 'ESH', 212, 'AF', 'Africa'),
            (250, 'YE', 'Yemen', 'YEM', 967, 'AS', 'Asia'),
            (251, 'ZM', 'Zambia', 'ZMB', 260, 'AF', 'Africa'),
            (252, 'ZW', 'Zimbabwe', 'ZWE', 263, 'AF', 'Africa');
        ");
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('countries');
    }
}
